name: Generate snake animation

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: pavan050505
          outputs: dist/github-contribution-grid-snake-dark.svg

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

      - uses: actions/checkout@v3

      - name: push snake svg to the output branch
        run: |
          mkdir -p output
          cp dist/github-contribution-grid-snake-dark.svg output/
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add output -A
          git commit -m "updated snake animation"
          git push
